#!/bin/bash

# Generate Chaos Experiment Report Script
# Automatically generates a comprehensive report from chaos experiments

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

NAMESPACE="${1:-dockerimagesloaded}"
REPORT_FILE="CHAOS-EXPERIMENT-REPORT-$(date +%Y%m%d-%H%M%S).md"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Generate Chaos Experiment Report${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${CYAN}Namespace:${NC} $NAMESPACE"
echo -e "${CYAN}Report File:${NC} $REPORT_FILE"
echo ""

# Check if namespace exists
if ! kubectl get namespace "$NAMESPACE" > /dev/null 2>&1; then
    echo -e "${RED}✗ Namespace '$NAMESPACE' does not exist${NC}"
    exit 1
fi

echo -e "${YELLOW}Collecting experiment data...${NC}"

# Collect data
POD_CHAOS_COUNT=$(kubectl get podchaos -n "$NAMESPACE" --no-headers 2>/dev/null | wc -l | tr -d ' ')
NETWORK_CHAOS_COUNT=$(kubectl get networkchaos -n "$NAMESPACE" --no-headers 2>/dev/null | wc -l | tr -d ' ')
STRESS_CHAOS_COUNT=$(kubectl get stresschaos -n "$NAMESPACE" --no-headers 2>/dev/null | wc -l | tr -d ' ')
SCHEDULE_COUNT=$(kubectl get schedule -n "$NAMESPACE" --no-headers 2>/dev/null | wc -l | tr -d ' ')
TOTAL_EXPERIMENTS=$((POD_CHAOS_COUNT + NETWORK_CHAOS_COUNT + STRESS_CHAOS_COUNT + SCHEDULE_COUNT))

APP_PODS=$(kubectl get pods -n "$NAMESPACE" -l app=resume-app --no-headers 2>/dev/null | wc -l | tr -d ' ')
READY_PODS=$(kubectl get pods -n "$NAMESPACE" -l app=resume-app --no-headers 2>/dev/null | grep -c "Running" || echo "0")

echo -e "${GREEN}✓ Data collected${NC}"
echo ""

# Generate report
cat > "$REPORT_FILE" << EOF
# Chaos Engineering Experiment Report

**Report Date:** $(date '+%B %d, %Y %H:%M:%S')  
**Cluster:** $(kubectl config current-context 2>/dev/null || echo "Unknown")
**Target Application:** resume-app  
**Namespace:** $NAMESPACE  
**Chaos Mesh Version:** $(kubectl get deployment chaos-controller-manager -n chaos-mesh -o jsonpath='{.metadata.labels.app\.kubernetes\.io/version}' 2>/dev/null || echo "Unknown")

---

## Executive Summary

This report documents the chaos engineering experiments conducted on the \`resume-app\` application using Chaos Mesh.

### Quick Statistics

- **Total Experiments:** $TOTAL_EXPERIMENTS
  - Pod Chaos: $POD_CHAOS_COUNT
  - Network Chaos: $NETWORK_CHAOS_COUNT
  - Stress Chaos: $STRESS_CHAOS_COUNT
  - Scheduled: $SCHEDULE_COUNT
- **Application Pods:** $APP_PODS (Ready: $READY_PODS)
- **Application Status:** $(if [ "$READY_PODS" -gt 0 ]; then echo "✅ Healthy"; else echo "⚠️ Issues"; fi)

---

## Active Experiments

### Pod Chaos Experiments

\`\`\`
$(kubectl get podchaos -n "$NAMESPACE" 2>/dev/null || echo "No pod chaos experiments found")
\`\`\`

### Network Chaos Experiments

\`\`\`
$(kubectl get networkchaos -n "$NAMESPACE" 2>/dev/null || echo "No network chaos experiments found")
\`\`\`

### Stress Chaos Experiments

\`\`\`
$(kubectl get stresschaos -n "$NAMESPACE" 2>/dev/null || echo "No stress chaos experiments found")
\`\`\`

### Scheduled Experiments

\`\`\`
$(kubectl get schedule -n "$NAMESPACE" 2>/dev/null || echo "No scheduled experiments found")
\`\`\`

---

## Application Status

### Current Pods

\`\`\`
$(kubectl get pods -n "$NAMESPACE" -l app=resume-app 2>/dev/null || echo "No pods found")
\`\`\`

### Deployment Status

\`\`\`
$(kubectl get deployment resume-app -n "$NAMESPACE" 2>/dev/null || echo "Deployment not found")
\`\`\`

---

## Recent Events

\`\`\`
$(kubectl get events -n "$NAMESPACE" --sort-by='.lastTimestamp' | grep -i chaos | tail -10 || echo "No recent chaos events")
\`\`\`

---

## Detailed Experiment Information

EOF

# Add detailed information for each experiment type
for chaos_type in podchaos networkchaos stresschaos; do
    echo "" >> "$REPORT_FILE"
    echo "### $(echo $chaos_type | sed 's/chaos/Chaos/') Details" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    
    for exp in $(kubectl get $chaos_type -n "$NAMESPACE" -o name 2>/dev/null); do
        echo "#### $exp" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
        echo "\`\`\`yaml" >> "$REPORT_FILE"
        kubectl get $exp -n "$NAMESPACE" -o yaml 2>/dev/null | head -50 >> "$REPORT_FILE"
        echo "\`\`\`" >> "$REPORT_FILE"
        echo "" >> "$REPORT_FILE"
    done
done

# Add footer
cat >> "$REPORT_FILE" << EOF
---

## Recommendations

1. Review experiment results and application behavior
2. Monitor application health during experiments
3. Document any issues or unexpected behaviors
4. Adjust experiment parameters based on findings

---

**Report Generated:** $(date '+%B %d, %Y %H:%M:%S')  
**Generated By:** generate-chaos-report.sh  
**Cluster:** $(kubectl config current-context 2>/dev/null || echo "Unknown")

EOF

echo -e "${GREEN}✓ Report generated: $REPORT_FILE${NC}"
echo ""
echo -e "${CYAN}View report:${NC}"
echo -e "  ${BLUE}cat $REPORT_FILE${NC}"
echo ""
