---
# I/O Stress Chaos Experiment
# Applies I/O stress to resume-app pods
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: resume-app-io-stress
  namespace: dockerimagesloaded
spec:
  mode: one
  selector:
    namespaces:
      - dockerimagesloaded
    labelSelectors:
      app: resume-app
  stressors:
    memory:
      workers: 1
      size: "128MB"
      options: ["--vm 1", "--vm-bytes 128M", "--vm-keep", "--timeout 60s"]
  duration: "45s"
